#!/usr/bin/perl

use strict;
use warnings;
use HTTP::Tiny;
use JSON::MaybeXS;

my $url = 'https://www.yahoo.com/news/weather/united-kingdom/england/london-44418';
my $http = HTTP::Tiny->new( default_headers => {
    'User-Agent' => 'Mozilla/5.0'
});
my $res = $http->get($url);
die "Failed to fetch page" unless $res->{success};

my $html = $res->{content};

# Extract JSON from the __NEXT_DATA__ <script> block
$html =~ m{<script[^>]*id="__NEXT_DATA__"[^>]*>(.*?)</script>}s
  or die "Couldn't find __NEXT_DATA__ script block";
my $json = $1;

my $data = decode_json($json);

# Drill down into current weather details
my $obs = $data->{props}{pageProps}{data}{currentObservation};
my $forecast = $data->{props}{pageProps}{data}{forecast}[0];

printf "Weather for London:\n";
printf "Condition   : %s\n", $obs->{condition}{text};
printf "Temperature : %s°C\n", $obs->{condition}{temperature};
printf "Humidity    : %s%%\n", $obs->{atmosphere}{humidity};
printf "Wind Speed  : %s km/h\n", $obs->{wind}{speed};
printf "High / Low  : %s°C / %s°C\n", $forecast->{high}, $forecast->{low};

